In [30]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [21]:
data = pd.read_csv('C:/Users/tk_42/AppData/Local/Programs/Python/Python39/Scripts/SoftwareDevTools/vehicles_us.csv')
data.sample(10, random_state=8384)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
36128,6440,2011.0,chevrolet cruze,excellent,NaN,gas,134.0,automatic,sedan,NaN,NaN,2019-01-31,68
48749,10900,2010.0,ram 1500,good,6.0,gas,NaN,automatic,pickup,grey,NaN,2018-07-12,55
13521,3100,2007.0,nissan sentra,fair,4.0,gas,65000.0,automatic,sedan,grey,NaN,2018-09-22,30
26827,5495,1994.0,chevrolet silverado,excellent,NaN,gas,191387.0,manual,pickup,white,1.0,2019-01-05,19
8803,4995,NaN,jeep grand cherokee,good,8.0,gas,155207.0,automatic,SUV,white,1.0,2018-12-23,22
13263,9500,2012.0,ford f150,good,8.0,gas,210377.0,automatic,truck,white,NaN,2019-01-28,30
45844,3200,2006.0,honda civic,good,4.0,gas,144000.0,manual,sedan,NaN,NaN,2018-07-24,107
1357,8000,2008.0,ford f-250 super duty,good,10.0,gas,240000.0,manual,truck,red,NaN,2019-04-13,49
29263,9500,2013.0,volkswagen passat,like new,6.0,diesel,78600.0,automatic,sedan,white,NaN,2018-06-08,7
25606,10600,2015.0,nissan rogue,excellent,4.0,gas,52000.0,automatic,SUV,grey,1.0,2018-09-05,31